config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "pages#home"

  resources :tips do
    member do
      put "like", to: "tips#upvote"
      put "dislike", to: "tips#downvote"
    end
  end

end

app/models/tip.rb
class Tip < ActiveRecord::Base
  acts_as_votable

  def self.search(search)
    if search
      where('content LIKE ?', "%#{search}%")
      where('title LIKE ?', "%#{search}%")
    end
  end

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all

    @search = params[:search]

    if @search.present?
      @tips = @tips.search(@search)
    end

    @tips = @tips.order('created_at ASC')

  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # Upvote
  def upvote
    @tip.upvote_by current_user
    redirect_to tips_path
  end

  # Downvote
  def downvote
    @tip.downvote_by current_user
    redirect_to tips_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:title, :content)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>HackathonApp</title>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <meta http-equiv="x-ua-compatible" content="ie=edge">
 <!-- include fonts -->
 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Baloo+Bhaina">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans">

 <!-- include bootstrap -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% elsif alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div>
    <h1>DURABLE</h1>
    <h2>Make it last!</h2>
    <div>
      <%= form_tag(tips_path, :method => "get", id: "search-input", class: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "", class: "search-form-textbox" %>
      <span class="button">
        <%= submit_tag "Search", class: "btn btn-success btn-lg" %>
      </span>
      <% end %>
    </div>
  </div>
</div>

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<h1>Editing Tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<h1>Tips</h1>


<% @tips.each do |tip| %>
<div class="card">
  <div class="card-body">
    <div class="card-section">
      <h3><%= tip.title %></h3>
      <p><%= tip.content %></p>
    </div>

    <div class="card-aside">
      <div class="card-section">

       Score: <%= tip.score %>

       <!-- Add comment, this does not have correct functionality but is for demo purposes -->
       <%= link_to 'Comment', edit_tip_path(tip) %>
       <%= link_to 'X', tip, method: :delete, data: { confirm: 'Are you sure?' } %>


         <%= link_to image_tag("like.png"), like_tip_path(tip), method: :put %>
       <%= link_to image_tag("dislike.png"),  dislike_tip_path(tip), method: :put %>

     </div>
   </div>
 </div>
</div>
<% end %>

<br>

<%= link_to '+', new_tip_path %>

app/views/tips/new.html.erb
<h1>New Tip</h1>

<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tip.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tip.content %>
</p>

<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>